export const FETCH_RESTAURANTS = 'FETCH_RESTAURANT';
export const FETCH_RESTAURANTS_SUCCESS = 'FETCH_RESTAURANT_SUCCESS';
export const CREAR_RESTAURANT = 'CREAR_RESTAURANT';
export const CREAR_RESTAURANT_SUCCESS = 'CREAR_RESTAURANT_SUCCESS';
export const GET_RESTAURANT = 'GET_RESTAURANT';
export const GET_RESTAURANT_ERROR = 'GET_RESTAURANT_ERROR';
export const EDITAR_RESTAURANT = 'EDITAR_RESTAURANT';
export const EDITAR_RESTAURANT_SUCCESS = 'EDITAR_RESTAURANT_SUCCESS';
export const EMPTY_RESTAURANT = 'EMPTY_RESTAURANT';

export const FETCH_PLATOS = 'FETCH_PLATOS';
export const FETCH_PLATOS_SUCCESS = 'FETCH_PLATOS_SUCCESS';
export const CREAR_PLATO = 'CREAR_PLATO';
export const CREAR_PLATO_SUCCESS = 'CREAR_PLATO_SUCCESS';
export const GET_PLATO = 'GET_PLATO';
export const EDITAR_PLATO = 'EDITAR_PLATO';
export const EDITAR_PLATO_SUCCESS = 'EDITAR_PLATO_SUCCESS';
export const EMPTY_PLATO = 'EMPTY_PLATO';


export const CREAR_MENSAJE = 'CREAR_MENSAJE';
export const CREAR_MENSAJE_SUCCESS = 'CREAR_MENSAJE_SUCCESS';
export const CREAR_MENSAJE_FAILED = 'CREAR_MENSAJE_FAILED';
